# version: '3.8'

volumes:
  db:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data

  budget_project:
    build: ./
    env_file: .env
    depends_on:
      - db
