# version: '3.8'

volumes:
  pg_data:
  static:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: avanslov/simbu_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - ./media:/app/budget_project/media/
    depends_on:
      - db

  gateway:
    image: avanslov/simbu_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
      - ./media:/app/budget_project/media/
    ports:
      - 6000:80
    depends_on:
      - backend
