# Generated by Django 4.2 on 2024-05-09 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bot.currency'),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rates_by_first_currency', to='bot.currency'),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_currency',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rates_by_second_currency', to='bot.currency'),
        ),
        migrations.AddField(
            model_name='usermaincurrency',
            name='main_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bot.currency'),
        ),
    ]
