# Generated by Django 3.2.16 on 2024-04-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(),
        ),
    ]
