# Generated by Django 4.2 on 2024-05-06 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UserMainCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('main_currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bot.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate_sell', models.FloatField()),
                ('rate_buy', models.FloatField()),
                ('first_currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rates_by_first_currency', to='bot.currency')),
                ('second_currency', models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rates_by_second_currency', to='bot.currency')),
            ],
        ),
        migrations.AddField(
            model_name='money',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bot.currency'),
        ),
    ]
