# Generated by Django 5.0.4 on 2024-04-26 07:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_expenses_expense_rename_incomes_income'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriesOfIncomes',
            new_name='CategoryOfExpenses',
        ),
        migrations.RenameModel(
            old_name='CategoriesOfExpenses',
            new_name='CategoryOfIncomes',
        ),
    ]
