# Generated by Django 4.2 on 2024-05-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_category_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ('date',)},
        ),
    ]
