# Generated by Django 4.2 on 2024-05-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_money_value_in_main_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='value_in_main_currency',
        ),
    ]
