# Generated by Django 5.0.4 on 2024-04-26 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_rename_categoriesofincomes_categoryofexpenses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'default_related_name': '%(class)s'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'default_related_name': '%(class)s'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.categoryofexpenses'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.categoryofincomes'),
        ),
    ]
