# Generated by Django 4.2 on 2024-05-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_money_value_in_main_currency'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('date', 'first_currency', 'second_currency'), name='unique_rate'),
        ),
    ]
